FROM httpd:2.4

# Copy custom configuration files into the Apache container
COPY httpd.conf /usr/local/apache2/conf/httpd.conf
COPY proxy-html.conf /usr/local/apache2/conf/extra/proxy-html.conf

# Copy frontend files into the Apache document root
COPY . /usr/local/apache2/htdocs/

# Expose HTTP port
EXPOSE 8080

# Start Apache server
CMD ["httpd-foreground"]
