kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
    - containerPort: 8080
      hostPort: 8080
      protocol: TCP
    - containerPort: 27017
      hostPort: 27017
      protocol: TCP
    - containerPort: 4000
      hostPort: 4000
      protocol: TCP
    - containerPort: 4001
      hostPort: 4001
      protocol: TCP
    - containerPort: 4002
      hostPort: 4002
      protocol: TCP
