apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: dailybugle
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: dailybugle
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: article-service
spec:
  selector:
    app: dailybugle
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
---
apiVersion: v1
kind: Service
metadata:
  name: ad-service
spec:
  selector:
    app: dailybugle
  ports:
    - protocol: TCP
      port: 4002
      targetPort: 4002
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: dailybugle
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort
