apiVersion: v1
kind: Pod
metadata:
  name: dailybugle-pod
spec:
  volumes:
  - name: task-pv-storage
    persistentVolumeClaim:
      claimName: task-pv-claim
  
  containers:
  - name: auth-service
    image: dailybugle-auth-service
    imagePullPolicy: Never
    ports:
    - containerPort: 4000
  
  - name: article-service
    image: dailybugle-article-service
    imagePullPolicy: Never
    ports:
    - containerPort: 4001
  
  - name: ad-service
    image: dailybugle-ad-service
    imagePullPolicy: Never
    ports:
    - containerPort: 4002
  
  - name: frontend
    image: dailybugle-frontend
    imagePullPolicy: Never
    ports:
    - containerPort: 8080
  
  - name: task-pv-container
    image: mongo
    ports:
    - containerPort: 27017
      name: mongoservice
    volumeMounts:
    - mountPath: /data/db
      name: task-pv-storage