apiVersion: v1
kind: Pod
metadata:
  name: dailybugle-pod
spec:
  containers:
  - name: mongo
    image: mongo:5.0
    ports:
    - containerPort: 27017
    volumeMounts:
    - name: mongo-data
      mountPath: /data/db

  - name: auth-service
    image: dailybugle-auth-service
    imagePullPolicy: Never # stops kind from pulling from public docker registry
    ports:
    - containerPort: 4000
    env:
    - name: MONGO_URI
      value: "mongodb://host.docker.internal:27017"

  - name: article-service
    image: dailybugle-article-service
    imagePullPolicy: Never
    ports:
    - containerPort: 4001
    env:
    - name: MONGO_URI
      value: "mongodb://host.docker.internal:27017"

  - name: ad-service
    image: dailybugle-ad-service
    imagePullPolicy: Never
    ports:
    - containerPort: 4002
    env:
    - name: MONGO_URI
      value: "mongodb://host.docker.internal:27017"

  - name: frontend
    image: dailybugle-frontend
    imagePullPolicy: Never
    ports:
    - containerPort: 8080

  volumes:
  - name: mongo-data
    emptyDir: {}
