# Use Node.js as the base image
FROM node:16

# Create and set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the application code
COPY . .

# Expose the port used by the service
EXPOSE 4000

# Command to start the application
CMD ["node", "auth.js"]
